### ISSUE TITLE
Install on Raspberry ends with "API is not responding (Error : 0 error)"

### ISSUE THREAD

**Issue by KojoePi** [YunoHost/doc#214]
Could someone please help? After installing yunohost on Raspbian the Webinterface tells me "API is not responding (Error : 0 error)" ..

Thanks in advance for helping

**Comment by M5oul** [comment]
You should ask your question of the [forum](http://forum.yunohost.org/).

**Comment by KojoePi** [comment]
Why? Where does it stand? You are offering github as your sourxe of code so you should answer wuestions here too. I wont register on your forum. Why do you think i want to selfhost stuff? Because i want my data under my control. THIS ISSUE IS JUST CLOSED NOT SOLDVED.
Thanks for your help.......nooooooottttt!

**Comment by M5oul** [comment]
Sorry for that radical solution. I think you will get more help on the forum or on the [IM](https://yunohost.org/#/) than here. Did you installed the rasp 2 image?
We host the forum, it's almost same confidence than GitHub.

**Comment by jeromelebleu** [comment]
@KojoePi Hi ! I agree with M5oul. Moreover, you've opened this issue at the wrong place, since here it's the repository of the documentation... I'll open a new one in the right repository, feel free to give more information there, or switch to the forum or the chat room!
