### ISSUE TITLE
Missing pages/link to unexisting ones: Gandi_fr and bookmyname_fr

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/doc#238]
Hello,

Here: https://yunohost.org/#/dns there are references to:

* https://yunohost.org/#/Gandi_fr
* https://yunohost.org/#/BookMyName_fr

In: "Vous pouvez également consulter les documentations spécifiques à ces différents registrar : OVH, Gandi, BookMyName."

But those 2 pages don't exist and I can't find them under a different name in the repository.

Kind regards,

**Comment by M5oul** [comment]
Thanks. Done https://github.com/YunoHost/doc/commit/279cb96fbcd7b962c9d224f009384a8ad386d6dd & https://github.com/YunoHost/doc/commit/605c9205d2456d9a507db36ba7254846d0f31613.
