### ISSUE TITLE
[DOC FR] certains Liens existant pointe sur erreur 404

### ISSUE THREAD

**Issue by benborges** [YunoHost/doc#282]
Répertorié sur cet page pour l'instant, j'en ajouterais si j'en trouve d'autre. 
https://github.com/YunoHost/doc/blob/master/install_on_dedicated_server_fr.md
aussi
https://github.com/YunoHost/doc/blob/master/install_on_debian_fr.md

**Comment by M5oul** [comment]
Ces pages fonctionnent bien dans mon cas : 
* https://yunohost.org/#/install_on_dedicated_server_fr
* https://yunohost.org/#/install_on_debian_fr

**Comment by isAAAc** [comment]
Le 2015-06-02 21:46, M5oul a écrit :
> Ces pages fonctionnent bien dans mon cas :
> * https://yunohost.org/#/install_on_dedicated_server_fr
> * https://yunohost.org/#/install_on_debian_fr

je confirme

isAAAc

**Comment by M5oul** [comment]
On est deux à confirmer. Je ferme l’issue.

**Comment by benborges** [comment]
en effet, les liens sont OK quand on passe par la doc sur le site Yunohost.org, mais les liens ne fonctionne pas quand on consulte la doc a partir de github.
