### ISSUE TITLE
Is 256MB of RAM the real minimum?

### ISSUE THREAD

**Issue by RyDroid** [YunoHost/doc#319]
Hi.
I created a server in Gandi with IaaS offer with 256MB of RAM. After installation, I could not update Debian due to seg fault error with "apt-get upgrade" so apparently 256MB is not enough. So I think that the minimum limit should be defined as 386MB.
It can easily found where there is the minimum with "grep -r 256". However it also matches sha256, so it should not be replaced automatically or with a stricter matching pattern.
Regards.

**Comment by M5oul** [comment]
256 Mio were for the raspberry one. It's just, and should works. but 512 Mio is recommanded.
