### ISSUE TITLE
Fix la brique tutorial about OSX

### ISSUE THREAD

**Issue by JocelynDelalande** [YunoHost/doc#325]
I know it's evil, but as [the tutorial](   https://github.com/YunoHost/doc/blob/master/installation_brique_fr.md) is saying…

    Et évidemment, un ordinateur sous UNIX (e.g. GNU/Linux).

… I tried using OSX, it quite does not work.

- the `dd` option is not `bs=1M` `bs=1m` on OSX
- the dd took very long and succeeed (don't know if it will fail on all OSX or just mine though)… but the olimex board refused to boot it (had no screen, so no debug, sorry)
- the `ls -1 /sys/block/`does not exist on OSX

I do no longer have any OSX machine to test it, so if some apple-user can confirm/infirm what I state, and maybe enhance the documentation, be welcome :)

It raises a more general question: is this documentation realy tested under other UNIXes that GNU/Linux ? If not, we should make it clear in the documentation, not pretending it will work ;-)

PS: heck that's quite weird to write in english about a french documentation...

**Comment by Kloadut** [comment]
Yup, Mac OS X not tested nor supported anyway.

Fixed as of https://github.com/YunoHost/doc/commit/a2b7902214743a0fae55fc41563c78f2c79d16bc

**Comment by JocelynDelalande** [comment]
> Yup, Mac OS X not tested nor supported anyway.

Ok, but what about other UNIXes, did we really tested ?

> Fixed as of a2b7902

Thanks for reactivity <3 you close issue as fast as I open them !

**Comment by Kloadut** [comment]
Well, FreeBSD works AFAIK. Even `arp-scan` is available
