### ISSUE TITLE
White page

### ISSUE THREAD

**Issue by zamentur** [YunoHost/doc#326]
On my Firefox the page is completely white there is javascript error:

https://yunohost.org/#/development_fr
https://yunohost.org/#/dev_fr

**Comment by Kloadut** [comment]
It is a markdown parsing error. Most of the time it is related to the code blocks: You have to indicate the code language on top of your blocks for syntax highlighing:

\`\`\`
console.log('yolo');
\`\`\`

```
console.log('yolo');
```

<br>


\`\`\`javascript
console.log('swag');
\`\`\`


```javascript
consol.log('swag');
```

**Comment by zamentur** [comment]
Thanks
