### ISSUE TITLE
Firefox won't open the admin interface

### ISSUE THREAD

**Issue by DamienCassou** [YunoHost/doc#328]
While following the documentation at https://github.com/YunoHost/doc/blob/master/installation_brique_fr.md#%C3%89tapes-de-configuration, I wrote the hostname of my cube in the Firefox address bar and got:

```
Secure Connection Failed

An error occurred during a connection to brique.cassou.me. You have received an invalid certificate. Please contact the server administrator or email correspondent and give them the following information: Your certificate contains the same serial number as another certificate issued by the certificate authority. Please get a new certificate containing a unique serial number. (Error code: sec_error_reused_issuer_and_serial)

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

The documentation says `accepter l'exception de sécurité du certificat` but Firefox won't allow that. This is different from other certificate problems I regularly face that can typically be ignored.

I'm blocked

**Comment by DamienCassou** [comment]
I found some documentation at: https://support.mozilla.org/fr/kb/resoudre-echec-connexion-securisee#w_le-certificat-contient-le-maeme-numaero-de-saerie-quun-autre-certificat

I solved my issue by removing some yunohost-related certificate exceptions in Firefox.

**Comment by Kloadut** [comment]
Yes it seems related to the fact that you had a previous instance installed with the same name.
