### ISSUE TITLE
No 'admin' user

### ISSUE THREAD

**Issue by DamienCassou** [YunoHost/doc#329]
In `installation_brique_fr`, it is said

> Pour ne garder que la connexion en tant qu’admin (qui est sudoer)

but the `admin` user is not on my system. I have created the first user on the yunohost admin interface.

**Comment by jvaubourg** [comment]
> Mettre à jour la configuration SSH : par défaut, la connexion en tant que root est possible sur la Brique. Pour ne garder que la connexion en tant qu’admin (qui est sudoer), il convient d’éditer le /etc/ssh/sshd_config et de passer PermitRootLogin à without-password.

L'utilisateur « admin » est un utilisateur Unix, et non un utilisateur YunoHost.

C'est une étape supplémentaire vraiment très facultative. Elle propose juste d'interdire à l'utilisateur Unix « root » de se connecter en SSH, au profit de l'utilisateur Unix « admin ». Ce dernier ayant les droits sudo, il pourra faire tout ce que root peut faire, mais en forçant la journalisation de ses actions.

Bref, oublie si tu ne comprends pas bien à quoi ça sert, c'est vraiment pas important :).

**Comment by DamienCassou** [comment]
Merci pour ta réponse. 

> L'utilisateur « admin » est un utilisateur Unix, et non un utilisateur YunoHost.

Je suis bien conscient de ça, mais il n'existe pas (ou en tout cas, je ne le vois pas dans `/etc/passwd`). À quel moment cet utilisateur doit il être créé ?

**Comment by jvaubourg** [comment]
Il existe déjà, il est créé à l'installation de YunoHost.

Tu ne le vois pas dans `/etc/passwd` parce que c'est un utilisateur enregistré dans LDAP. Pour voir tous les utilisateurs que ton système connaît, tu peux utiliser la commande `getent passwd`.

**Comment by DamienCassou** [comment]
Super merci beaucoup.

**Comment by DamienCassou** [comment]
Tentative de documentation suite à tes réponses : https://github.com/YunoHost/doc/pull/330
